env:
  - CGO_ENABLED=0
  - PROJECT=github.com/cloudradar-monitoring/frontman
builds:
- main: ./cmd/frontman
  binary: frontman
  goos:
  - windows
  - darwin
  - linux
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  - mipsle
  goarm:
  - 5
  - 6
  - 7
  gomips:
  - hardfloat
  - softfloat
  # List of combinations of GOOS + GOARCH + GOARM to ignore.
  ignore:
  - goos: darwin
    goarch: 386
  - goos: windows
    goarch: 386
  - goos: windows
    goarch: arm
  - goos: darwin
    goarch: arm
  - goos: windows
    goarch: arm64
  - goos: darwin
    goarch: arm64
  - goos: darwin
    goarch: mipsle
  - goos: windows
    goarch: mipsle
  ldflags:
    - "-s -w  -X {{.Env.PROJECT}}.Version={{.Version}} -X \"{{.Env.PROJECT}}.SelfUpdatesFeedURL={{.Env.SELF_UPDATES_FEED_URL}}\""
archives:
  -
    files:
    - README.md
    - example.json
    - example.config.toml
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpms:
  -
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"

    vendor: cloudradar GmbH
    maintainer: CloudRadar GmbH <frontman@cloudradar.io>
    homepage: https://cloudradar.io
    description: Monitoring proxy for agentless monitoring of subnets
    license: MIT

    # Formats to be generated.
    formats:
    - deb
    - rpm

    recommends:
    - ca-certificates
    - procps

    # Override default /usr/local/bin destination for binaries
    bindir: /usr/bin

    # Empty folders that should be created and managed by the packager
    # implementation.
    empty_folders:
    - /var/log/frontman
    - /etc/frontman
    - /usr/share/frontman

    # Put example.json
    files:
      "example.json": "/usr/share/doc/frontman/example.json"
      "example.config.toml": "/etc/frontman/example.config.toml"
      "cacert.pem": "/etc/frontman/cacert.pem"
      "pkg-scripts/frontman.tt": "/etc/frontman/frontman.tt"

    scripts:
      preinstall: "pkg-scripts/preinstall.sh"
      postinstall: "pkg-scripts/postinstall.sh"
      preremove: "pkg-scripts/preremove.sh"

    overrides:
      rpm:
        recommends:
        - ca-certificates
        - procps-ng
        dependencies:
        - libcap
        scripts:
          postinstall: "pkg-scripts/postinstall-rpm.sh"
          preremove: "pkg-scripts/preremove-rpm.sh"
      deb:
        dependencies:
        - libcap2-bin
release:
  github:
    owner: cloudradar-monitoring
    name: frontman
  draft: true
