[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "github.com/troian/toml"
  version = "0.3.2"

[[constraint]]
  name = "gopkg.in/ldap.v2"
  version = "2.5.1"

[[constraint]]
  name = "github.com/kardianos/service"
  revision = "c1c4306577988c5b299c64af2f0ccea15d1f7d54"
  source = "github.com/cloudradar-monitoring/service"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.6"

[[constraint]]
  name = "github.com/shirou/gopsutil"
  version = "2.19.03"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "github.com/lxn/win"
  revision = "6f00d814e89c2442495334cdd91bb6ff3003eeb7"

[[constraint]]
  name = "github.com/lxn/walk"
  revision = "6cf0bf1359a5d99a8160321be78b61e7b635e324"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/toast.v1"

[[constraint]]
  name = "github.com/soniah/gosnmp"
  revision = "1b12be15031c65438aa78efb424e8e335f16f539"
