---
version: 2
jobs:
  test:
    docker:
      - image: cloudradario/go-build:0.0.8
    working_directory: /go/src/github.com/cloudradar-monitoring/frontman
    steps:
      - checkout
      - run: make test
  
  gorelease:
    docker:
      - image: cloudradario/go-build:0.0.8
    working_directory: /go/src/github.com/cloudradar-monitoring/frontman
    steps:
      # Setup our ssh key from env var to be able to connect to Windows VM
      - run: echo $WIN_SSH_KEY | base64 -d > /tmp/id_win_ssh
      - run: chmod 0600 /tmp/id_win_ssh
      - checkout
      # Build binaries
      - run: make goreleaser-rm-dist
      # Create remote build dir
      - run: make ci
      - run:
          shell: /bin/bash
          command: |
            if [[ ${CIRCLE_TAG} =~ -{1}((0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$ ]] ; then
              github-release edit --user cloudradar-monitoring --repo frontman --tag ${CIRCLE_TAG} --pre-release 
            else
              github-release edit --user cloudradar-monitoring --repo frontman --tag ${CIRCLE_TAG}
            fi
  
  goreleasse-test:
    docker:
      - image: cloudradario/go-build:0.0.8
    working_directory: /go/src/github.com/cloudradar-monitoring/frontman
    steps:
      - checkout
      - run: make goreleaser-snapshot

workflows:
  version: 2
  test-on-commit:
    jobs:
      - test:
          filters:
            tags:
              ignore: /.*/
      - goreleasse-test:
          filters:
            tags:
              ignore: /.*/
  
  test-and-release:
    jobs:
      - test:
          filters:
            tags:
              only: /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/
            branches:
              ignore: /.*/
      - gorelease:
          requires:
            - test
          filters:
            tags:
              only: /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/
            branches:
              ignore: /.*/
