---
version: 2
jobs:
  test:
    docker:
      - image: cloudradario/go-build:0.0.6
    working_directory: /go/src/github.com/cloudradar-monitoring/frontman
    steps:
      - checkout
      - run: go test $(go list ./... | grep -v /vendor/)  
  
  gorelease:
    docker:
      - image: cloudradario/go-build:0.0.6
    working_directory: /go/src/github.com/cloudradar-monitoring/frontman
    steps:
      # Setup our ssh key from env var to be able to connect to Windows VM
      - run: echo $WIN_SSH_KEY | base64 -d > /tmp/id_win_ssh
      - run: chmod 0600 /tmp/id_win_ssh
      - checkout
      # Build binaries
      - run: goreleaser --rm-dist
      # Since goreleaser can't handle pre-releases as we need it we mark it later as pre-release using github-release
      - run:
          shell: /bin/bash
          command: |
           if [[ ${CIRCLE_TAG} =~ -{1}((0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$ ]] ; then github-release edit --user cloudradar-monitoring --repo frontman --tag ${CIRCLE_TAG} -p; fi
      # Create remote build dir
      - run: ssh -i /tmp/id_win_ssh -oStrictHostKeyChecking=no hero@13.80.137.211 mkdir -p /cygdrive/c/Users/hero/frontman_ci/build_msi/${CIRCLE_BUILD_NUM}/dist
      # Copy exe files to Windows VM for bundingling and signing
      - run: scp -i /tmp/id_win_ssh -oStrictHostKeyChecking=no /go/src/github.com/cloudradar-monitoring/frontman/dist/windows_386/frontman.exe  hero@13.80.137.211:/cygdrive/c/Users/hero/frontman_ci/build_msi/${CIRCLE_BUILD_NUM}/dist/frontman_386.exe
      - run: scp -i /tmp/id_win_ssh -oStrictHostKeyChecking=no /go/src/github.com/cloudradar-monitoring/frontman/dist/windows_amd64/frontman.exe hero@13.80.137.211:/cygdrive/c/Users/hero/frontman_ci/build_msi/${CIRCLE_BUILD_NUM}/dist/frontman_64.exe
      # Copy other build dependencies
      - run: scp -i /tmp/id_win_ssh -oStrictHostKeyChecking=no /go/src/github.com/cloudradar-monitoring/frontman/build-win.bat hero@13.80.137.211:/cygdrive/c/Users/hero/frontman_ci/build_msi/${CIRCLE_BUILD_NUM}/build-win.bat
      - run: ssh -i /tmp/id_win_ssh -oStrictHostKeyChecking=no hero@13.80.137.211 chmod +x /cygdrive/c/Users/hero/frontman_ci/build_msi/${CIRCLE_BUILD_NUM}/build-win.bat
      - run: scp -r -i /tmp/id_win_ssh -oStrictHostKeyChecking=no /go/src/github.com/cloudradar-monitoring/frontman/pkg-scripts/  hero@13.80.137.211:/cygdrive/c/Users/hero/frontman_ci/build_msi/${CIRCLE_BUILD_NUM}
      - run: scp -i /tmp/id_win_ssh -oStrictHostKeyChecking=no /go/src/github.com/cloudradar-monitoring/frontman/example.config.toml hero@13.80.137.211:/cygdrive/c/Users/hero/frontman_ci/build_msi/${CIRCLE_BUILD_NUM}/example.config.toml
      - run: scp -i /tmp/id_win_ssh -oStrictHostKeyChecking=no /go/src/github.com/cloudradar-monitoring/frontman/example.json hero@13.80.137.211:/cygdrive/c/Users/hero/frontman_ci/build_msi/${CIRCLE_BUILD_NUM}/example.json
      - run: scp -i /tmp/id_win_ssh -oStrictHostKeyChecking=no /go/src/github.com/cloudradar-monitoring/frontman/LICENSE hero@13.80.137.211:/cygdrive/c/Users/hero/frontman_ci/build_msi/${CIRCLE_BUILD_NUM}/LICENSE
      - run: scp -i /tmp/id_win_ssh -oStrictHostKeyChecking=no /go/src/github.com/cloudradar-monitoring/frontman/wix.json hero@13.80.137.211:/cygdrive/c/Users/hero/frontman_ci/build_msi/${CIRCLE_BUILD_NUM}/wix.json
      # Trigger msi creating and signing
      - run: ssh -i /tmp/id_win_ssh -oStrictHostKeyChecking=no hero@13.80.137.211 /cygdrive/c/Users/hero/frontman_ci/build_msi/${CIRCLE_BUILD_NUM}/build-win.bat ${CIRCLE_BUILD_NUM} ${CIRCLE_TAG} ${SIGN_CERT_PASS}
      # Copy msi files back to build machine
      - run: scp -i /tmp/id_win_ssh -oStrictHostKeyChecking=no hero@13.80.137.211:/cygdrive/c/Users/hero/frontman_ci/build_msi/${CIRCLE_BUILD_NUM}/dist/frontman_32.msi /go/src/github.com/cloudradar-monitoring/frontman/dist/frontman_386.msi
      - run: scp -i /tmp/id_win_ssh -oStrictHostKeyChecking=no hero@13.80.137.211:/cygdrive/c/Users/hero/frontman_ci/build_msi/${CIRCLE_BUILD_NUM}/dist/frontman_64.msi /go/src/github.com/cloudradar-monitoring/frontman/dist/frontman_64.msi
      # Add files to Github release
      - run: github-release upload --user cloudradar-monitoring --repo frontman --tag ${CIRCLE_TAG} --name "frontman_${CIRCLE_TAG}_Windows_386.msi" --file "/go/src/github.com/cloudradar-monitoring/frontman/dist/frontman_386.msi"
      - run: github-release upload --user cloudradar-monitoring --repo frontman --tag ${CIRCLE_TAG} --name "frontman_${CIRCLE_TAG}_Windows_x86_64.msi" --file "/go/src/github.com/cloudradar-monitoring/frontman/dist/frontman_64.msi"
  
  goreleasse-test:
    docker:
      - image: cloudradario/go-build:0.0.6
    working_directory: /go/src/github.com/cloudradar-monitoring/frontman
    steps:
      - checkout
      - run: goreleaser --snapshot

workflows:
  version: 2
  test-on-commit:
    jobs:
      - test:
          filters:
            tags:
              ignore: /.*/
      - goreleasse-test:
          filters:
            tags:
              ignore: /.*/
  
  test-and-release:
    jobs:
      - test:
          filters:
            tags:
              only: /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/
            branches:
              ignore: /.*/
      - gorelease:
          requires:
            - test
          filters:
            tags:
              only: /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/
            branches:
              ignore: /.*/
