---
version: 2.1

orbs:
  ms-teams: cloudradar-monitoring/ms-teams@0.0.1

docker_job_setup: &docker_job
  docker:
    - image: cloudradario/go-build:0.0.16
  working_directory: /go/src/github.com/cloudradar-monitoring/frontman

attach_workspace: &workspace
  attach_workspace:
    at: /go/src/github.com/cloudradar-monitoring

common_workflow_setup: &common_workflow
  context: cloudradar
  post-steps:
    - ms-teams/report:
        only_on_fail: true
        webhook_url: $MS_TEAMS_WEBHOOK_URL

jobs:
  get-source:
    <<: *docker_job
    steps:
      - checkout
      - persist_to_workspace:
          root: /go/src/github.com/cloudradar-monitoring
          paths:
            - frontman

  test:
    <<: *docker_job
    steps:
      - <<: *workspace
      - run: make test

  test-goreleaser:
    <<: *docker_job
    steps:
      - <<: *workspace
      - run: make goreleaser-snapshot

  build-goreleaser:
    <<: *docker_job
    steps:
      - <<: *workspace
      - run:
          name: Build binaries
          command: make goreleaser-rm-dist
      - persist_to_workspace:
          root: /go/src/github.com/cloudradar-monitoring
          paths:
            - frontman

  build-docker:
    <<: *docker_job
    steps:
      - <<: *workspace
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.06.3-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: |
          docker login --username ${DOCKERHUB_USER} --password ${DOCKERHUB_PASS}
          docker build --build-arg FRONTMAN_VERSION=${CIRCLE_TAG} -t cloudradario/frontman:${CIRCLE_TAG} .
          docker push cloudradario/frontman:${CIRCLE_TAG}

  build-sign-msi:
    <<: *docker_job
    steps:
      - <<: *workspace
      - add_ssh_keys:
          fingerprints:
            - "b3:b7:b0:59:57:1a:bc:82:6c:3c:91:d6:23:19:f2:08"
      - run:
          name: Sign msi files
          command: make windows-sign

  build-aptly:
    <<: *docker_job
    steps:
      - <<: *workspace
      - add_ssh_keys:
          fingerprints:
            - "53:d2:08:dc:1a:4e:9e:29:00:d4:ba:1e:b7:5d:16:25"
      - run:
          name: Update aptly repository
          command: make aptly

  build-createrepo:
    <<: *docker_job
    steps:
      - <<: *workspace
      - add_ssh_keys:
          fingerprints:
            - "53:d2:08:dc:1a:4e:9e:29:00:d4:ba:1e:b7:5d:16:25"
      - run:
          name: Update createrepo repository
          command: make createrepo

  release-github:
    <<: *docker_job
    steps:
      - run:
          name: Fetch release changelog so we can preserve it when releasing
          command: "CHANGELOGRAW=$(curl -H \"Authorization: token ${GITHUB_TOKEN}\"  https://api.github.com/repos/cloudradar-monitoring/frontman/releases | jq \".[0].body\") && echo \"export CHANGELOGRAW=$CHANGELOGRAW\" >> $BASH_ENV"
      - run:
          name: Publish release
          shell: /bin/bash
          command: |
            if [[ ${CIRCLE_TAG} =~ -{1}((0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$ ]] ; then
              echo -e ${CHANGELOGRAW} | github-release edit --user cloudradar-monitoring --repo frontman --tag ${CIRCLE_TAG} --pre-release --description -
            else
              echo -e ${CHANGELOGRAW} | github-release edit --user cloudradar-monitoring --repo frontman --tag ${CIRCLE_TAG} --description -
            fi
          when: on_success
      - run:
          name: Delete GitHub release in case something went wrong
          command: github-release delete --user cloudradar-monitoring --repo frontman --tag ${CIRCLE_TAG}
          when: on_fail

  build-synology-spk:
    <<: *docker_job
    steps:
      - <<: *workspace
      - run:
          name: Build Synology packages
          command: make synology-spk

workflows:
  version: 2
  test-on-commit:
    jobs:
      - get-source:
          <<: *common_workflow
          filters:
            tags:
              ignore: /.*/
      - test:
          <<: *common_workflow
          requires:
            - get-source
          filters:
            tags:
              ignore: /.*/
      - test-goreleaser:
          <<: *common_workflow
          requires:
            - get-source
          filters:
            tags:
              ignore: /.*/

  release:
    jobs:
      - get-source:
          <<: *common_workflow
          filters:
            tags:
              only: /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/
            branches:
              ignore: /.*/
      - test:
          <<: *common_workflow
          requires:
            - get-source
          filters:
            tags:
              only: /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/
            branches:
              ignore: /.*/
      - build-goreleaser:
          <<: *common_workflow
          requires:
            - test
          filters:
            tags:
              only: /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/
            branches:
              ignore: /.*/
      - build-sign-msi:
          <<: *common_workflow
          requires:
            - build-goreleaser
          filters:
            tags:
              only: /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/
            branches:
              ignore: /.*/
      - build-aptly:
          <<: *common_workflow
          requires:
            - build-goreleaser
          filters:
            tags:
              only: /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/
            branches:
              ignore: /.*/
      - build-createrepo:
          <<: *common_workflow
          requires:
            - build-goreleaser
          filters:
            tags:
              only: /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/
            branches:
              ignore: /.*/
      - release-github:
          <<: *common_workflow
          requires:
            - build-sign-msi
            - build-synology-spk
          filters:
            tags:
              only: /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/
            branches:
              ignore: /.*/
      - build-docker:
          <<: *common_workflow
          requires:
            - release-github
          filters:
            tags:
              only: /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/
            branches:
              ignore: /.*/
      - build-synology-spk:
          <<: *common_workflow
          requires:
            - build-goreleaser
          filters:
            tags:
              only: /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/
            branches:
              ignore: /.*/
